// ==================== DATABASE ====================
let database = {
  users: [
    {
      id: 1,
      name: "Admin User",
      email: "admin@hungryHouse.com",
      password: "admin123",
      phone: "9876543210",
      role: "admin",
    },
    {
      id: 2,
      name: "Rajesh Kumar",
      email: "rajesh@example.com",
      password: "rajesh123",
      phone: "9876543211",
      role: "user",
    },
    {
      id: 3,
      name: "Priya Sharma",
      email: "priya@example.com",
      password: "priya123",
      phone: "9876543212",
      role: "user",
    },
  ],

  foodItems: [
    {
      id: 1,
      name: "Paneer Tikka",
      description: "Grilled cottage cheese cubes marinated in spices",
      price: 299,
      offerPrice: 249,
      category: "starters",
      image:
        "https://images.unsplash.com/photo-1606491956689-2ea866880c84?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60",
      isAvailable: true,
      isOffer: true,
    },
    {
      id: 2,
      name: "Chicken Tikka",
      description: "Tender chicken pieces marinated in yogurt and spices",
      price: 349,
      offerPrice: null,
      category: "starters",
      image:
        "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60",
      isAvailable: true,
      isOffer: false,
    },
    {
      id: 3,
      name: "Butter Chicken",
      description: "Tender chicken in rich tomato and butter gravy",
      price: 399,
      offerPrice: 349,
      category: "main-course",
      image:
        "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60",
      isAvailable: true,
      isOffer: true,
    },
    {
      id: 4,
      name: "Paneer Butter Masala",
      description: "Cottage cheese cubes in creamy tomato gravy",
      price: 329,
      offerPrice: null,
      category: "main-course",
      image:
        "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60",
      isAvailable: true,
      isOffer: false,
    },
    {
      id: 5,
      name: "Dal Makhani",
      description: "Black lentils cooked overnight with butter and cream",
      price: 279,
      offerPrice: 239,
      category: "main-course",
      image:
        "https://images.unsplash.com/photo-1585937421612-70ca003675ed?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60",
      isAvailable: true,
      isOffer: true,
    },
    {
      id: 6,
      name: "Veg Biryani",
      description: "Fragrant basmati rice cooked with mixed vegetables",
      price: 299,
      offerPrice: null,
      category: "main-course",
      image:
        "https://images.unsplash.com/photo-1563379091339-03246963d9d6?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60",
      isAvailable: true,
      isOffer: false,
    },
    {
      id: 7,
      name: "Chicken Biryani",
      description: "Aromatic basmati rice with tender chicken pieces",
      price: 349,
      offerPrice: 299,
      category: "main-course",
      image:
        "https://images.unsplash.com/photo-1633945274405-b6c8069047b0?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60",
      isAvailable: true,
      isOffer: true,
    },
    {
      id: 8,
      name: "Butter Naan",
      description: "Soft leavened bread brushed with butter",
      price: 59,
      offerPrice: null,
      category: "breads",
      image:
        "https://images.unsplash.com/photo-1601050690597-df0568f70950?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60",
      isAvailable: true,
      isOffer: false,
    },
    {
      id: 9,
      name: "Garlic Naan",
      description: "Naan stuffed with garlic and coriander",
      price: 79,
      offerPrice: 69,
      category: "breads",
      image:
        "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60",
      isAvailable: true,
      isOffer: true,
    },
    {
      id: 10,
      name: "Roti",
      description: "Whole wheat Indian flatbread",
      price: 25,
      offerPrice: null,
      category: "breads",
      image:
        "https://images.unsplash.com/photo-1505253668822-42074d58a7c6?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60",
      isAvailable: true,
      isOffer: false,
    },
    {
      id: 11,
      name: "Gulab Jamun",
      description: "Deep fried milk solids in sugar syrup",
      price: 129,
      offerPrice: 99,
      category: "desserts",
      image:
        "https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60",
      isAvailable: true,
      isOffer: true,
    },
    {
      id: 12,
      name: "Rasmalai",
      description: "Soft cheese patties in sweetened milk",
      price: 149,
      offerPrice: null,
      category: "desserts",
      image:
        "https://images.unsplash.com/photo-1603532648955-039310d9ed75?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60",
      isAvailable: true,
      isOffer: false,
    },
  ],

  offers: [
    {
      id: 1,
      title: "Weekend Special",
      code: "WEEKEND20",
      discount: 20,
      description: "Get 20% off on all orders above ₹500",
      validUntil: "2024-12-31",
      isActive: true,
    },
    {
      id: 2,
      title: "First Order",
      code: "FIRSTORDER",
      discount: 15,
      description: "15% off on your first order",
      validUntil: "2024-12-31",
      isActive: true,
    },
    {
      id: 3,
      title: "Family Deal",
      code: "FAMILY30",
      discount: 30,
      description: "30% off on orders above ₹1000",
      validUntil: "2024-11-30",
      isActive: true,
    },
  ],

  tables: [
    { id: 1, number: 1, seats: 2, status: "available", currentOrder: null },
    { id: 2, number: 2, seats: 2, status: "available", currentOrder: null },
    { id: 3, number: 3, seats: 4, status: "available", currentOrder: null },
    { id: 4, number: 4, seats: 4, status: "available", currentOrder: null },
    { id: 5, number: 5, seats: 6, status: "available", currentOrder: null },
    { id: 6, number: 6, seats: 6, status: "available", currentOrder: null },
  ],

  orders: [
    {
      id: 1,
      userId: 2,
      type: "delivery",
      items: [
        { foodId: 1, quantity: 2, name: "Paneer Tikka", price: 249 },
        { foodId: 11, quantity: 1, name: "Gulab Jamun", price: 99 },
      ],
      subtotal: 597,
      tax: 107.46,
      delivery: 49,
      total: 753.46,
      status: "delivered",
      date: "2024-10-15",
      customerName: "Rajesh Kumar",
      customerPhone: "9876543211",
      address: "123 Andheri West, Mumbai - 400001",
      paymentMethod: "card",
    },
    {
      id: 2,
      userId: 3,
      type: "dine-in",
      items: [
        { foodId: 3, quantity: 1, name: "Butter Chicken", price: 349 },
        { foodId: 9, quantity: 2, name: "Garlic Naan", price: 69 },
      ],
      subtotal: 487,
      tax: 87.66,
      delivery: 0,
      total: 574.66,
      status: "preparing",
      date: "2024-10-16",
      customerName: "Priya Sharma",
      customerPhone: "9876543212",
      tableNumber: 3,
      numberOfGuests: 2,
      paymentMethod: "cash",
    },
  ],
};

// ==================== APPLICATION STATE ====================
let appState = {
  isLoggedIn: false,
  isAdmin: false,
  currentUser: null,
  cart: [],
  currentSection: "home",
  currentCategory: "all",
  isSearching: false,
  searchTerm: "",
  orderType: null,
  dineInDetails: null,
  appliedOffer: null,
  discountAmount: 0,
  discountPercent: 0,
};
